# Source/Destination directories
src_dir: /
dst_dir: /mnt/backup
# Paths to exclude. Please note that excluded paths are RELATIVE to src_dir
# if you plan to use absolute paths, set absolute_paths to true
excluded:
    - "dev/*"
    - "proc/*"
    - "sys/*"
    - "tmp/*"
    - "run/*"
    - "mnt/*"
    - "media/*"
    - "lost+found"
daily_dir: daily
weekly_dir: weekly
monthly_dir: monthly
last_file: .last
log_path: /tmp/backup.log

# rsync args
rsync_args:
    - "-aAXv"
    - "--delete"
    - "--info=progress2"

# pysync settings
ignore_mountpoint_warning: false
absolute_paths: false